import { NextResponse } from "next/server";

// PDF Export Engine — serverless-compatible (puppeteer-core + @sparticuz/chromium)
// Generates vector-quality, downloadable PDFs with professional layout
export const maxDuration = 60;

export async function POST(req) {
  let browser = null;

  try {
    const chromium = (await import("@sparticuz/chromium")).default;
    const puppeteer = (await import("puppeteer-core")).default;

    const body = await req.json();
    const { reportData, fileName, language } = body;

    if (!reportData) {
      return NextResponse.json(
        { error: "No report data provided" },
        { status: 400 }
      );
    }

    console.log("[PDF Export] Starting PDF generation...");

    // Launch serverless Chromium
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: { width: 1200, height: 1600, deviceScaleFactor: 2 },
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();

    // Generate HTML content for PDF
    const htmlContent = generatePDFHTML(reportData, language || "en");

    // Use base64 data URL to avoid ByteString encoding issues with non-ASCII
    // characters (Czech: č, ž, ř, etc.) in page.setContent()
    const base64Html = Buffer.from(htmlContent, "utf-8").toString("base64");
    await page.goto(`data:text/html;charset=utf-8;base64,${base64Html}`, {
      waitUntil: "networkidle0",
    });
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Generate PDF with professional settings
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "2cm",
        right: "1.5cm",
        bottom: "2cm",
        left: "1.5cm",
      },
      displayHeaderFooter: true,
      headerTemplate: "<div></div>",
      footerTemplate: `
        <div style="font-size: 8pt; color: #94a3b8; text-align: center; width: 100%; padding: 10px;">
          <span style="margin-right: 20px;">Generated by DataPalo AI</span>
          <span style="margin-right: 20px;">|</span>
          <span style="margin-right: 20px;">forgecreative.cz/datapalo</span>
          <span style="margin-left: 30px; color: #cbd5e1;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
      preferCSSPageSize: false,
    });

    await browser.close();
    browser = null;

    console.log(
      `[PDF Export] PDF generated successfully (${(pdfBuffer.length / 1024).toFixed(0)} KB)`
    );

    // Return PDF file as downloadable attachment
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${sanitizeFileName(fileName || "DataPalo_Report")}_${new Date().toISOString().slice(0, 10)}.pdf"`,
        "Content-Length": pdfBuffer.length.toString(),
      },
    });
  } catch (error) {
    console.error("[PDF Export] Error:", error);

    if (browser) {
      try {
        await browser.close();
      } catch (_) {}
    }

    return NextResponse.json(
      { error: error.message || "PDF generation failed" },
      { status: 500 }
    );
  }
}

// Sanitize file name for Content-Disposition header (ASCII-only required)
function sanitizeFileName(name) {
  return String(name)
    .normalize("NFD")                      // decompose: č → c + combining mark
    .replace(/[\u0300-\u036f]/g, "")       // strip combining diacritical marks
    .replace(/[^a-zA-Z0-9 _\-]/g, "")     // keep only ASCII-safe chars
    .replace(/\s+/g, "_")
    .slice(0, 100);
}

// ────────────────────────────────────────────────────────────────
//  HTML generator — full professional report layout
// ────────────────────────────────────────────────────────────────

function generatePDFHTML(reportData, language) {
  const title = reportData.title || "Data Analysis Report";
  const summary = reportData.summary || "";
  const metrics = reportData.metrics || [];
  const charts = reportData.charts || [];
  const insights = reportData.insights || [];
  const research = reportData.research || null;

  return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      color: #1e293b;
      line-height: 1.6;
      background: white;
    }

    .container { max-width: 100%; padding: 0; }

    /* Header */
    .header {
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 3px solid #0ea5e9;
    }
    .header h1 { font-size: 28pt; font-weight: bold; color: #0f172a; margin-bottom: 12px; }
    .header .summary { font-size: 11pt; color: #475569; line-height: 1.6; }
    .header .meta { font-size: 9pt; color: #94a3b8; margin-top: 10px; }

    /* Metrics Grid */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
      margin-bottom: 30px;
      page-break-inside: avoid;
    }
    .metric-card {
      background: #f8fafc;
      border: 1px solid #cbd5e1;
      border-left: 4px solid #0ea5e9;
      border-radius: 6px;
      padding: 16px;
      page-break-inside: avoid;
    }
    .metric-card .label { font-size: 9pt; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
    .metric-card .value { font-size: 22pt; font-weight: bold; color: #0f172a; margin-bottom: 4px; }
    .metric-card .description { font-size: 9pt; color: #64748b; margin-top: 8px; }

    /* Section Headers */
    .section-header {
      font-size: 16pt; font-weight: 600; color: #1e293b;
      margin: 30px 0 20px 0;
      padding-bottom: 8px;
      border-bottom: 2px solid #e2e8f0;
      page-break-after: avoid;
    }

    /* Charts */
    .chart-container {
      background: white;
      border: 1px solid #e2e8f0;
      border-radius: 6px;
      padding: 20px;
      margin-bottom: 20px;
      page-break-inside: avoid;
    }
    .chart-container h3 { font-size: 13pt; color: #1e293b; margin-bottom: 16px; }

    /* Insights */
    .insight-card {
      background: white;
      border: 1px solid #cbd5e1;
      border-left-width: 3px;
      border-radius: 6px;
      padding: 16px;
      margin-bottom: 16px;
      page-break-inside: avoid;
    }
    .insight-card.critical { border-left-color: #ef4444; }
    .insight-card.warning  { border-left-color: #f59e0b; }
    .insight-card.success  { border-left-color: #10b981; }
    .insight-card.info     { border-left-color: #3b82f6; }
    .insight-card h4 { font-size: 11pt; font-weight: 600; color: #1e293b; margin-bottom: 8px; }
    .insight-card p  { font-size: 10pt; color: #475569; line-height: 1.6; }

    /* Research Section */
    .research-box {
      background: #f0fdf4;
      border: 1px solid #86efac;
      border-radius: 6px;
      padding: 20px;
      margin-bottom: 20px;
      page-break-inside: avoid;
    }
    .research-box h4 { font-size: 11pt; color: #166534; margin-bottom: 10px; }
    .research-box p { font-size: 10pt; color: #15803d; line-height: 1.6; }
    .research-box .source { font-size: 8pt; color: #4ade80; margin-top: 6px; }

    /* Tables */
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { background: #f1f5f9; color: #0f172a; font-weight: 600; font-size: 9pt; padding: 10px; border: 1px solid #cbd5e1; text-align: left; }
    td { font-size: 9pt; color: #334155; padding: 8px 10px; border: 1px solid #e2e8f0; }
    tbody tr:nth-child(even) { background: #f8fafc; }

    .page-break { page-break-before: always; }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>${escapeHtml(title)}</h1>
      <p class="summary">${escapeHtml(summary)}</p>
      <p class="meta">Generated by DataPalo AI &bull; ${new Date().toLocaleDateString(language === "cs" ? "cs-CZ" : "en-GB")} &bull; forgecreative.cz/datapalo</p>
    </div>

    <!-- Key Metrics -->
    ${
      metrics.length > 0
        ? `
      <h2 class="section-header">${language === "cs" ? "Klíčové Metriky" : "Key Metrics"}</h2>
      <div class="metrics-grid">
        ${metrics
          .map(
            (metric) => `
          <div class="metric-card">
            <div class="label">${escapeHtml(metric.label || "")}</div>
            <div class="value">${escapeHtml(metric.value || "")}</div>
            ${metric.description ? `<div class="description">${escapeHtml(metric.description)}</div>` : ""}
          </div>
        `
          )
          .join("")}
      </div>
    `
        : ""
    }

    <!-- Charts -->
    ${
      charts.length > 0
        ? `
      <h2 class="section-header">${language === "cs" ? "Vizualizace" : "Visualizations"}</h2>
      ${charts.map((chart, index) => generateChartHTML(chart, index)).join("")}
    `
        : ""
    }

    <!-- Research -->
    ${
      research
        ? `
      <h2 class="section-header page-break">${language === "cs" ? "Výzkum a Kontekst" : "Research & Context"}</h2>
      ${
        research.benchmarks
          ? `<div class="research-box"><h4>${language === "cs" ? "Oborové Benchmarky" : "Industry Benchmarks"}</h4><p>${escapeHtml(research.benchmarks)}</p></div>`
          : ""
      }
      ${
        research.trends
          ? `<div class="research-box"><h4>${language === "cs" ? "Tržní Trendy" : "Market Trends"}</h4><p>${escapeHtml(research.trends)}</p></div>`
          : ""
      }
      ${
        research.sources && research.sources.length > 0
          ? `<div class="research-box"><h4>${language === "cs" ? "Citované Zdroje" : "Cited Sources"}</h4>${research.sources.map((s) => `<p class="source">${escapeHtml(typeof s === "string" ? s : s.title || s.url || "")}</p>`).join("")}</div>`
          : ""
      }
    `
        : ""
    }

    <!-- Insights -->
    ${
      insights.length > 0
        ? `
      <h2 class="section-header page-break">${language === "cs" ? "Poznatky a Doporučení" : "Insights & Recommendations"}</h2>
      <div class="insights-container">
        ${insights
          .map(
            (insight) => `
          <div class="insight-card ${insight.severity || "info"}">
            <h4>${escapeHtml(insight.title || "")}</h4>
            <p>${escapeHtml(insight.content || "")}</p>
          </div>
        `
          )
          .join("")}
      </div>
    `
        : ""
    }
  </div>
</body>
</html>
  `;
}

// ────────────────────────────────────────────────────────────────
//  SVG Chart generators (static, suitable for PDF)
// ────────────────────────────────────────────────────────────────

function generateChartHTML(chart, index) {
  const chartType = chart.chartType || chart.type || "bar";
  const data = chart.data || [];
  const title = chart.title || `Chart ${index + 1}`;

  if (chartType === "bar") return generateBarChartSVG(title, data, chart);
  if (chartType === "line") return generateLineChartSVG(title, data, chart);
  if (chartType === "pie") return generatePieChartSVG(title, data, chart);

  return `<div class="chart-container"><h3>${escapeHtml(title)}</h3><p>Chart visualization</p></div>`;
}

function generateBarChartSVG(title, data, chart) {
  if (!data || data.length === 0) return "";

  const dataKeys = chart.dataKeys || [
    { name: Object.keys(data[0])[0], value: Object.keys(data[0])[1] },
  ];
  const nameKey = dataKeys[0].name;
  const valueKey = dataKeys[0].value;

  const maxValue = Math.max(...data.map((d) => parseFloat(d[valueKey]) || 0));
  const barWidth = 600 / data.length - 20;
  const colors = ["#3b82f6", "#10b981", "#8b5cf6", "#f59e0b", "#ef4444"];

  const bars = data
    .map((item, index) => {
      const value = parseFloat(item[valueKey]) || 0;
      const height = (value / maxValue) * 200;
      const x = index * (barWidth + 20) + 40;
      const y = 250 - height;

      return `
      <rect x="${x}" y="${y}" width="${barWidth}" height="${height}" fill="${colors[index % colors.length]}" rx="4"/>
      <text x="${x + barWidth / 2}" y="270" text-anchor="middle" font-size="10" fill="#475569">${escapeHtml(String(item[nameKey]).slice(0, 15))}</text>
      <text x="${x + barWidth / 2}" y="${y - 5}" text-anchor="middle" font-size="10" font-weight="bold" fill="#1e293b">${value}</text>
    `;
    })
    .join("");

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <svg width="100%" height="300" viewBox="0 0 700 300">${bars}<line x1="30" y1="250" x2="670" y2="250" stroke="#cbd5e1" stroke-width="1"/></svg>
    </div>
  `;
}

function generateLineChartSVG(title, data, chart) {
  if (!data || data.length === 0) return "";

  const dataKeys = chart.dataKeys || [
    { name: Object.keys(data[0])[0], value: Object.keys(data[0])[1] },
  ];
  const valueKey = dataKeys[0].value;
  const nameKey = dataKeys[0].name;

  const maxValue = Math.max(...data.map((d) => parseFloat(d[valueKey]) || 0));
  const stepX = 600 / (data.length - 1 || 1);

  const points = data
    .map((item, index) => {
      const value = parseFloat(item[valueKey]) || 0;
      const x = index * stepX + 50;
      const y = 250 - (value / maxValue) * 200;
      return `${x},${y}`;
    })
    .join(" ");

  const labels = data
    .map((item, index) => {
      const x = index * stepX + 50;
      return `<text x="${x}" y="270" text-anchor="middle" font-size="10" fill="#475569">${escapeHtml(String(item[nameKey]).slice(0, 15))}</text>`;
    })
    .join("");

  const dots = data
    .map((item, index) => {
      const value = parseFloat(item[valueKey]) || 0;
      const x = index * stepX + 50;
      const y = 250 - (value / maxValue) * 200;
      return `<circle cx="${x}" cy="${y}" r="4" fill="#3b82f6"/>`;
    })
    .join("");

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <svg width="100%" height="300" viewBox="0 0 700 300">
        <polyline points="${points}" fill="none" stroke="#3b82f6" stroke-width="2"/>${dots}${labels}
        <line x1="40" y1="250" x2="660" y2="250" stroke="#cbd5e1" stroke-width="1"/>
      </svg>
    </div>
  `;
}

function generatePieChartSVG(title, data, chart) {
  if (!data || data.length === 0) return "";

  const dataKeys = chart.dataKeys || [
    { name: Object.keys(data[0])[0], value: Object.keys(data[0])[1] },
  ];
  const valueKey = dataKeys[0].value;
  const nameKey = dataKeys[0].name;

  const total = data.reduce(
    (sum, item) => sum + (parseFloat(item[valueKey]) || 0),
    0
  );
  const colors = ["#3b82f6", "#10b981", "#8b5cf6", "#f59e0b", "#ef4444"];

  let currentAngle = -90;
  const slices = data
    .map((item, index) => {
      const value = parseFloat(item[valueKey]) || 0;
      const angle = (value / total) * 360;

      const startAngle = currentAngle;
      const endAngle = currentAngle + angle;
      currentAngle = endAngle;

      const startRad = (startAngle * Math.PI) / 180;
      const endRad = (endAngle * Math.PI) / 180;

      const x1 = 150 + 80 * Math.cos(startRad);
      const y1 = 150 + 80 * Math.sin(startRad);
      const x2 = 150 + 80 * Math.cos(endRad);
      const y2 = 150 + 80 * Math.sin(endRad);

      const largeArc = angle > 180 ? 1 : 0;

      return `<path d="M 150 150 L ${x1} ${y1} A 80 80 0 ${largeArc} 1 ${x2} ${y2} Z" fill="${colors[index % colors.length]}"/>`;
    })
    .join("");

  const legend = data
    .map((item, index) => {
      return `
      <div style="display: flex; align-items: center; margin: 4px 0;">
        <div style="width: 12px; height: 12px; background: ${colors[index % colors.length]}; margin-right: 8px; border-radius: 2px;"></div>
        <span style="font-size: 9pt; color: #475569;">${escapeHtml(String(item[nameKey]))} (${((parseFloat(item[valueKey]) / total) * 100).toFixed(1)}%)</span>
      </div>
    `;
    })
    .join("");

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <div style="display: flex; align-items: center; justify-content: space-around;">
        <svg width="300" height="300" viewBox="0 0 300 300">${slices}</svg>
        <div>${legend}</div>
      </div>
    </div>
  `;
}

// Escape HTML to prevent XSS
function escapeHtml(text) {
  const map = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return String(text).replace(/[&<>"']/g, (m) => map[m]);
}
