import { NextResponse } from "next/server";

// PDF Export Engine - Server-side Playwright
// Generates vector-quality PDFs with professional layout
export const maxDuration = 60;

export async function POST(req) {
  let browser = null;

  try {
    // Dynamic import to avoid build-time resolution issues
    const { chromium } = await import("playwright");

    const body = await req.json();
    const { reportData, fileName, language } = body;

    if (!reportData) {
      return NextResponse.json(
        { error: "No report data provided" },
        { status: 400 }
      );
    }

    console.log("[PDF Export] Starting PDF generation...");

    // Launch headless browser
    browser = await chromium.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const context = await browser.newContext({
      viewport: { width: 1200, height: 1600 },
      deviceScaleFactor: 2, // High DPI for vector quality
    });

    const page = await context.newPage();

    // Generate HTML content for PDF
    const htmlContent = generatePDFHTML(reportData, language || 'en');

    // Set page content
    await page.setContent(htmlContent, {
      waitUntil: 'networkidle'
    });

    // Wait for charts to render
    await page.waitForTimeout(2000);

    // Generate PDF with professional settings
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '2cm',
        right: '1.5cm',
        bottom: '2cm',
        left: '1.5cm'
      },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 8pt; color: #94a3b8; text-align: center; width: 100%; padding: 10px;">
          <span style="margin-right: 20px;">Generated by DataWizard AI</span>
          <span style="margin-right: 20px;">•</span>
          <span style="margin-right: 20px;">Trusted Intelligence for European SMEs</span>
          <span style="margin-right: 20px;">•</span>
          <span>forgecreative.cz/datawizard</span>
          <span style="margin-left: 30px; color: #cbd5e1;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
      preferCSSPageSize: false,
    });

    await browser.close();
    browser = null;

    console.log("[PDF Export] PDF generated successfully");

    // Return PDF file
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fileName || 'DataWizard_Report'}_${new Date().toISOString().slice(0, 10)}.pdf"`,
        'Content-Length': pdfBuffer.length.toString(),
      },
    });

  } catch (error) {
    console.error("[PDF Export] Error:", error);

    if (browser) {
      await browser.close();
    }

    return NextResponse.json(
      { error: error.message || "PDF generation failed" },
      { status: 500 }
    );
  }
}

// Generate professional HTML for PDF
function generatePDFHTML(reportData, language) {
  const title = reportData.title || 'Data Analysis Report';
  const summary = reportData.summary || '';
  const metrics = reportData.metrics || [];
  const charts = reportData.charts || [];
  const insights = reportData.insights || [];

  return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <script src="https://cdn.jsdelivr.net/npm/recharts@2.5.0/dist/Recharts.js"></script>
  <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      color: #1e293b;
      line-height: 1.6;
      background: white;
    }

    .container {
      max-width: 100%;
      padding: 0;
    }

    /* Header */
    .header {
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 3px solid #0ea5e9;
    }

    .header h1 {
      font-size: 28pt;
      font-weight: bold;
      color: #0f172a;
      margin-bottom: 12px;
    }

    .header .summary {
      font-size: 11pt;
      color: #475569;
      line-height: 1.6;
    }

    /* Metrics Grid */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
      margin-bottom: 30px;
      page-break-inside: avoid;
    }

    .metric-card {
      background: #f8fafc;
      border: 1px solid #cbd5e1;
      border-left: 4px solid #0ea5e9;
      border-radius: 6px;
      padding: 16px;
      page-break-inside: avoid;
    }

    .metric-card .label {
      font-size: 9pt;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 8px;
    }

    .metric-card .value {
      font-size: 22pt;
      font-weight: bold;
      color: #0f172a;
      margin-bottom: 4px;
    }

    .metric-card .description {
      font-size: 9pt;
      color: #64748b;
      margin-top: 8px;
    }

    /* Section Headers */
    .section-header {
      font-size: 16pt;
      font-weight: 600;
      color: #1e293b;
      margin: 30px 0 20px 0;
      padding-bottom: 8px;
      border-bottom: 2px solid #e2e8f0;
      page-break-after: avoid;
    }

    /* Charts */
    .chart-container {
      background: white;
      border: 1px solid #e2e8f0;
      border-radius: 6px;
      padding: 20px;
      margin-bottom: 20px;
      page-break-inside: avoid;
    }

    .chart-container h3 {
      font-size: 13pt;
      color: #1e293b;
      margin-bottom: 16px;
    }

    .chart-wrapper {
      width: 100%;
      height: 300px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    /* Insights */
    .insights-container {
      margin-top: 30px;
    }

    .insight-card {
      background: white;
      border: 1px solid #cbd5e1;
      border-left-width: 3px;
      border-radius: 6px;
      padding: 16px;
      margin-bottom: 16px;
      page-break-inside: avoid;
    }

    .insight-card.critical {
      border-left-color: #ef4444;
    }

    .insight-card.warning {
      border-left-color: #f59e0b;
    }

    .insight-card.success {
      border-left-color: #10b981;
    }

    .insight-card.info {
      border-left-color: #3b82f6;
    }

    .insight-card h4 {
      font-size: 11pt;
      font-weight: 600;
      color: #1e293b;
      margin-bottom: 8px;
    }

    .insight-card p {
      font-size: 10pt;
      color: #475569;
      line-height: 1.6;
    }

    /* Page breaks */
    .page-break {
      page-break-before: always;
    }

    /* Tables */
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }

    th {
      background: #f1f5f9;
      color: #0f172a;
      font-weight: 600;
      font-size: 9pt;
      padding: 10px;
      border: 1px solid #cbd5e1;
      text-align: left;
    }

    td {
      font-size: 9pt;
      color: #334155;
      padding: 8px 10px;
      border: 1px solid #e2e8f0;
    }

    tbody tr:nth-child(even) {
      background: #f8fafc;
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>${escapeHtml(title)}</h1>
      <p class="summary">${escapeHtml(summary)}</p>
    </div>

    <!-- Key Metrics -->
    ${metrics.length > 0 ? `
      <h2 class="section-header">${language === 'cs' ? 'Klíčové Metriky' : 'Key Metrics'}</h2>
      <div class="metrics-grid">
        ${metrics.map(metric => `
          <div class="metric-card">
            <div class="label">${escapeHtml(metric.label || '')}</div>
            <div class="value">${escapeHtml(metric.value || '')}</div>
            ${metric.description ? `<div class="description">${escapeHtml(metric.description)}</div>` : ''}
          </div>
        `).join('')}
      </div>
    ` : ''}

    <!-- Charts -->
    ${charts.length > 0 ? `
      <h2 class="section-header">${language === 'cs' ? 'Vizualizace' : 'Visualizations'}</h2>
      ${charts.map((chart, index) => generateChartHTML(chart, index)).join('')}
    ` : ''}

    <!-- Insights -->
    ${insights.length > 0 ? `
      <h2 class="section-header page-break">${language === 'cs' ? 'Poznatky' : 'Insights'}</h2>
      <div class="insights-container">
        ${insights.map(insight => `
          <div class="insight-card ${insight.severity || 'info'}">
            <h4>${escapeHtml(insight.title || '')}</h4>
            <p>${escapeHtml(insight.content || '')}</p>
          </div>
        `).join('')}
      </div>
    ` : ''}
  </div>
</body>
</html>
  `;
}

// Generate HTML for charts (simplified for PDF)
function generateChartHTML(chart, index) {
  const chartType = chart.chartType || chart.type || 'bar';
  const data = chart.data || [];
  const title = chart.title || `Chart ${index + 1}`;

  // For PDF, we'll use SVG-based simple charts
  if (chartType === 'bar') {
    return generateBarChartSVG(title, data, chart);
  } else if (chartType === 'line') {
    return generateLineChartSVG(title, data, chart);
  } else if (chartType === 'pie') {
    return generatePieChartSVG(title, data, chart);
  }

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <p>Chart visualization</p>
    </div>
  `;
}

// Simple SVG bar chart generator
function generateBarChartSVG(title, data, chart) {
  if (!data || data.length === 0) return '';

  const dataKeys = chart.dataKeys || [{ name: Object.keys(data[0])[0], value: Object.keys(data[0])[1] }];
  const nameKey = dataKeys[0].name;
  const valueKey = dataKeys[0].value;

  const maxValue = Math.max(...data.map(d => parseFloat(d[valueKey]) || 0));
  const barWidth = 600 / data.length - 20;
  const colors = ['#3b82f6', '#10b981', '#8b5cf6', '#f59e0b', '#ef4444'];

  const bars = data.map((item, index) => {
    const value = parseFloat(item[valueKey]) || 0;
    const height = (value / maxValue) * 200;
    const x = index * (barWidth + 20) + 40;
    const y = 250 - height;

    return `
      <rect x="${x}" y="${y}" width="${barWidth}" height="${height}" fill="${colors[index % colors.length]}" rx="4"/>
      <text x="${x + barWidth/2}" y="270" text-anchor="middle" font-size="10" fill="#475569">${escapeHtml(String(item[nameKey]))}</text>
      <text x="${x + barWidth/2}" y="${y - 5}" text-anchor="middle" font-size="10" font-weight="bold" fill="#1e293b">${value}</text>
    `;
  }).join('');

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <svg width="100%" height="300" viewBox="0 0 700 300">
        ${bars}
        <line x1="30" y1="250" x2="670" y2="250" stroke="#cbd5e1" stroke-width="1"/>
      </svg>
    </div>
  `;
}

// Simple SVG line chart generator
function generateLineChartSVG(title, data, chart) {
  if (!data || data.length === 0) return '';

  const dataKeys = chart.dataKeys || [{ name: Object.keys(data[0])[0], value: Object.keys(data[0])[1] }];
  const valueKey = dataKeys[0].value;
  const nameKey = dataKeys[0].name;

  const maxValue = Math.max(...data.map(d => parseFloat(d[valueKey]) || 0));
  const stepX = 600 / (data.length - 1 || 1);

  const points = data.map((item, index) => {
    const value = parseFloat(item[valueKey]) || 0;
    const x = index * stepX + 50;
    const y = 250 - (value / maxValue) * 200;
    return `${x},${y}`;
  }).join(' ');

  const labels = data.map((item, index) => {
    const x = index * stepX + 50;
    return `<text x="${x}" y="270" text-anchor="middle" font-size="10" fill="#475569">${escapeHtml(String(item[nameKey]))}</text>`;
  }).join('');

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <svg width="100%" height="300" viewBox="0 0 700 300">
        <polyline points="${points}" fill="none" stroke="#3b82f6" stroke-width="2"/>
        ${data.map((item, index) => {
          const value = parseFloat(item[valueKey]) || 0;
          const x = index * stepX + 50;
          const y = 250 - (value / maxValue) * 200;
          return `<circle cx="${x}" cy="${y}" r="4" fill="#3b82f6"/>`;
        }).join('')}
        ${labels}
        <line x1="40" y1="250" x2="660" y2="250" stroke="#cbd5e1" stroke-width="1"/>
      </svg>
    </div>
  `;
}

// Simple SVG pie chart generator
function generatePieChartSVG(title, data, chart) {
  if (!data || data.length === 0) return '';

  const dataKeys = chart.dataKeys || [{ name: Object.keys(data[0])[0], value: Object.keys(data[0])[1] }];
  const valueKey = dataKeys[0].value;
  const nameKey = dataKeys[0].name;

  const total = data.reduce((sum, item) => sum + (parseFloat(item[valueKey]) || 0), 0);
  const colors = ['#3b82f6', '#10b981', '#8b5cf6', '#f59e0b', '#ef4444'];

  let currentAngle = -90;
  const slices = data.map((item, index) => {
    const value = parseFloat(item[valueKey]) || 0;
    const percentage = (value / total) * 100;
    const angle = (value / total) * 360;

    const startAngle = currentAngle;
    const endAngle = currentAngle + angle;
    currentAngle = endAngle;

    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;

    const x1 = 150 + 80 * Math.cos(startRad);
    const y1 = 150 + 80 * Math.sin(startRad);
    const x2 = 150 + 80 * Math.cos(endRad);
    const y2 = 150 + 80 * Math.sin(endRad);

    const largeArc = angle > 180 ? 1 : 0;

    return `
      <path d="M 150 150 L ${x1} ${y1} A 80 80 0 ${largeArc} 1 ${x2} ${y2} Z" fill="${colors[index % colors.length]}"/>
    `;
  }).join('');

  const legend = data.map((item, index) => {
    return `
      <div style="display: flex; align-items: center; margin: 4px 0;">
        <div style="width: 12px; height: 12px; background: ${colors[index % colors.length]}; margin-right: 8px; border-radius: 2px;"></div>
        <span style="font-size: 9pt; color: #475569;">${escapeHtml(String(item[nameKey]))} (${((parseFloat(item[valueKey]) / total) * 100).toFixed(1)}%)</span>
      </div>
    `;
  }).join('');

  return `
    <div class="chart-container">
      <h3>${escapeHtml(title)}</h3>
      <div style="display: flex; align-items: center; justify-content: space-around;">
        <svg width="300" height="300" viewBox="0 0 300 300">
          ${slices}
        </svg>
        <div>
          ${legend}
        </div>
      </div>
    </div>
  `;
}

// Escape HTML to prevent XSS
function escapeHtml(text) {
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return String(text).replace(/[&<>"']/g, m => map[m]);
}
